language: php
php:
  - "5.5"
  - "5.4"
  - "5.3.3"
matrix:
  fast_finish: true
branches:
  only:
    - master
env:
  - CLOSURE_COMPILER=/tmp/compiler.jar
before_script:
  - ./scripts/travis/setup.sh
  - php -i
script:
  - ./scripts/travis/run-tests.sh
after_script:
  - "[ -f vendor/bin/coveralls ] && php vendor/bin/coveralls -v"