language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"
matrix:
  allow_failures:
    - php: "5.5"
before_script:
  - "php ./scripts/convert5.3.php"
  - "[[ `php -v` == PHP\\ 5.3* ]] && pecl install xslcache || exit 0"
branches:
  only: master