language: php
php: "5.5"
branches:
  only:
    - master
    - dev/php5.4
    - dev/php5.3
env:
  - CLOSURE_COMPILER=/tmp/compiler.jar
before_script:
  - sh -c "./scripts/travis/installComposer.sh 2>&1 &" >/dev/null 2>&1 &
  - ./scripts/travis/installClosureCompiler.sh         >/dev/null 2>&1 &
  - ./scripts/travis/installXSLCache.sh                >/dev/null 2>&1 &
  - mkdir tests/.cache
  - wait
  - php -i
script:
  - phpunit --exclude-group none --coverage-clover /tmp/clover.xml
after_script:
  - php vendor/bin/coveralls -v