sudo: false
language: php
matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: COVERAGE=1
    - php: 5.3.3
      env: OPTIMIZE=1
    - php: 5.4
      env: OPTIMIZE=1
    - php: 5.5
      env: OPTIMIZE=1
    - php: 5.6
      env: OPTIMIZE=1
    - php: hhvm
      env: OPTIMIZE=1
    - php: nightly
      env: OPTIMIZE=1
branches:
  only:
    - master
before_script:
  - ./scripts/travis/setup.sh
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then php -i; fi"
script:
  - ./scripts/travis/run-tests.sh
after_script:
  - ./scripts/travis/uploadCodeCoverage.sh