language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"
before_script:
  - "php ./scripts/convert5.3.php"
  - "[[ `php -v` == PHP\\ 5.5* ]] && sed -i '/<exclude>/,/<\\/exclude>/d' phpunit.xml || echo 'Kept excluded groups'"
branches:
  only: master