language: php
php:
  - "5.5"
  - "5.4"
  - "5.3.3"
before_script:
  - phpenv config-rm xdebug.ini
  - sh -c "echo 'zend.enable_gc=off' >> ~/.phpenv/versions/$TRAVIS_PHP_VERSION/etc/php.ini"
  - sh -c "wget -O - http://dl.google.com/closure-compiler/compiler-latest.tar.gz | tar xzf - -C/tmp compiler.jar"
  - sh -c "printf '\n' | pecl install xslcache-beta"
  - php ./scripts/build/patchSources.php
  - php -i
script: "CLOSURE_COMPILER=/tmp/compiler.jar phpunit --exclude-group needs-network"