language: php
php:
  - "5.5"
  - "5.4"
  - "5.3.3"
before_script:
  - "php ./scripts/convert5.3.php"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' = '5.3' ]; then printf '\n' | pecl install xslcache-beta; fi"
script: "phpunit --exclude-group needs-network"
branches:
  only: master