language: php
php:
  - "5.5"
  - "5.4"
  - "5.3.3"
before_script:
  - php ./scripts/build/patchSources.php
  - sh -c "wget -O - http://dl.google.com/closure-compiler/compiler-latest.tar.gz | tar xzf - -C/tmp compiler.jar"
  - sh -c "printf '\n' | pecl install xslcache-beta"
script: "CLOSURE_COMPILER=/tmp/compiler.jar phpunit --exclude-group needs-network"