language: php
php:
  - 5.5
  - 5.4
  - 5.3.3
  - hhvm
matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
branches:
  only:
    - master
env:
  - CLOSURE_COMPILER=/tmp/compiler.jar
before_script:
  - ./scripts/travis/setup.sh
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then php -i; fi"
script:
  - ./scripts/travis/run-tests.sh
after_script:
  - "[ -f vendor/bin/coveralls ] && php vendor/bin/coveralls --exclude-no-stmt -n -v"