language: php
php:
  - "5.5"
  - "5.4"
  - "5.3.3"
matrix:
  fast_finish: true
branches:
  only:
    - master
env:
  - CLOSURE_COMPILER=/tmp/compiler.jar
before_script:
  - ./scripts/travis/setup.sh
  - php -i
script:
  - "[ '$TRAVIS_PHP_VERSION' = '5.5' ] && phpunit --exclude-group none --coverage-clover /tmp/clover.xml"
  - "[ '$TRAVIS_PHP_VERSION' = '5.5' ] || phpunit --exclude-group needs-network"
after_script:
  - "[ -f vendor/bin/coveralls ] && php vendor/bin/coveralls -v"