language: php
php: "5.5"
env:
  - CLOSURE_COMPILER=/tmp/compiler.jar
before_script:
  - echo "zend.enable_gc=off" >> ~/.phpenv/versions/$TRAVIS_PHP_VERSION/etc/php.ini
  - sh -c "wget -O - http://dl.google.com/closure-compiler/compiler-latest.tar.gz | tar xzf - -C/tmp compiler.jar"
  - sh -c "printf '\n' | pecl install xslcache-beta"
  - php -i
  - composer install --dev --no-interaction
script:
  - phpunit --exclude-group needs-network --coverage-clover /tmp/clover.xml
after_script:
  - php vendor/bin/coveralls