language: php
php:
  - "5.5"
  - "5.4"
  - "5.3.3"
before_script:
  - sh -c "[ $TRAVIS_PHP_VERSION = '5.3.3' ] && rm /home/travis/.phpenv/versions/5.3.3/etc/conf.d/xdebug.ini"
  - sh -c "wget -O - http://dl.google.com/closure-compiler/compiler-latest.tar.gz | tar xzf - -C/tmp compiler.jar"
  - sh -c "printf '\n' | pecl install xslcache-beta"
  - php ./scripts/build/patchSources.php
  - php -i
script: "CLOSURE_COMPILER=/tmp/compiler.jar phpunit --exclude-group needs-network"