language: php
php: "5.5"
env:
  - CLOSURE_COMPILER=/tmp/compiler.jar
before_script:
  - echo "zend.enable_gc=off" >> ~/.phpenv/versions/$TRAVIS_PHP_VERSION/etc/php.ini
  - ./scripts/travis/installComposer.sh        >/dev/null 2>&1 &
  - ./scripts/travis/installClosureCompiler.sh >/dev/null 2>&1 &
  - ./scripts/travis/installXSLCache.sh        >/dev/null 2>&1 &
  - wait
  - php -i
script:
  - phpunit tests/Plugins/Emoticons