language: php
php:
  - "5.5"
  - "5.4"
  - "5.3.3"
before_script:
  - php ./scripts/build/patchSources.php
  - sh -c "printf '\n' | pecl install xslcache-beta; fi"
script: "phpunit --exclude-group needs-network"