language: php
php:
  - 5.5
  - 5.4
  - 5.3.3
  - hhvm
env:
  matrix:
    - OPTIMIZE=1
matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
  include:
    - php: 5.5
      env: OPTIMIZE= COVERAGE=1
branches:
  only:
    - master
before_script:
  - ./scripts/travis/setup.sh
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then php -i; fi"
script:
  - ./scripts/travis/run-tests.sh
after_script:
  - ./scripts/travis/uploadCodeCoverage.sh