site_name: s9e\TextFormatter
theme: readthedocs
repo_url: https://github.com/s9e/TextFormatter/
pages:
  - Home: index.md
  - Getting started:
    - Installation: Getting_started/Installation.md
    - How it works: Getting_started/How_it_works.md
    - Using predefined bundles: Getting_started/Using_predefined_bundles.md
    - Runtime configuration: Getting_started/Runtime_configuration.md
  - Templating:
    - Introduction: Templating/Introduction.md
    - Modify a template: Templating/Modify_a_template.md
    - Template parameters: Templating/Template_parameters.md
  - Rules:
    - Tag rules: Rules/Tag_rules.md
    - Automatic rules generation: Rules/Automatic_rules_generation.md
    - Rules generators: Rules/Rules_generators.md
  - Plugins:
    - Autoemail:
      - Synopsis: Plugins/Autoemail/Synopsis.md
    - Autolink:
      - Synopsis: Plugins/Autolink/Synopsis.md
    - BBCodes:
      - Synopsis: Plugins/BBCodes/Synopsis.md
      - Add from the repository: Plugins/BBCodes/Add_from_the_repository.md
      - Add custom BBCodes: Plugins/BBCodes/Add_custom_BBCodes.md
      - Custom BBCode syntax: Plugins/BBCodes/Custom_BBCode_syntax.md
      - Localize strings: Plugins/BBCodes/Localize_strings.md
      - Use template parameters: Plugins/BBCodes/Use_template_parameters.md
    - Censor:
      - Synopsis: Plugins/Censor/Synopsis.md
      - Whitelist: Plugins/Censor/Whitelist.md
      - As a standalone: Plugins/Censor/Standalone.md
      - Quick reparsing: Plugins/Censor/Reparse.md
    - Emoji:
      - Synopsis: Plugins/Emoji/Synopsis.md
    - Emoticons:
      - Synopsis: Plugins/Emoticons/Synopsis.md
      - Add emoticons: Plugins/Emoticons/Add_emoticons.md
      - Toggle rendering: Plugins/Emoticons/Toggle_rendering.md
      - Change the matching regexp: Plugins/Emoticons/Change_regexp.md
    - FancyPants:
      - Synopsis: Plugins/FancyPants/Synopsis.md
    - HTMLComments:
      - Synopsis: Plugins/HTMLComments/Synopsis.md
    - HTMLElements:
      - Synopsis: Plugins/HTMLElements/Synopsis.md
      - Alias HTML elements to other tags: Plugins/HTMLElements/Aliases.md
    - HTMLEntities:
      - Synopsis: Plugins/HTMLEntities/Synopsis.md
    - Keywords:
      - Synopsis: Plugins/Keywords/Synopsis.md
      - Map keywords to IDs: Plugins/Keywords/Map.md
      - Automatically link MTG cards: Plugins/Keywords/MTG.md
    - Litedown:
      - Synopsis: Plugins/Litedown/Synopsis.md
    - MediaEmbed:
      - Synopsis: Plugins/MediaEmbed/Synopsis.md
    - Preg:
      - Synopsis: Plugins/Preg/Synopsis.md
